# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and DOTNET_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: .Net app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: bp-calc-personal-acc       
  AZURE_WEBAPP_PACKAGE_PATH: 'publish' 

on:
  workflow_dispatch:  

# on:   
#   push:                            
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  create_webapp:
    uses: ./.github/workflows/deploy-app-azure.yml
    secrets: inherit #this passes secrets to the reusable workflow

  build_test:
    name: build and execute unit & BDD test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests (Standard)
      run: dotnet test BPUnitTest/BPUnitTest.csproj --verbosity normal -l:trx
    - name: Run BDD tests (Renqnroll perviously specflow)
      run: dotnet test BDDTesting/BDDTesting.csproj  --verbosity normal -l:trx

  code_analysis:
    needs: [build_test]
    uses: ./.github/workflows/sonar-code-analysis.yml # execite sonar code analysis in SonarQube Cloud
    secrets: inherit # this passes secrets to the reusable workflow

  dependency_check:
    needs: [build_test]
    uses: ./.github/workflows/dependency-check.yml # execute OWASP Dependency Checker 

  build:
    name: build and deploy app
    needs: [dependency_check, code_analysis, create_webapp]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release --property:PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PERSONAL_ACCOUNT }}
            
    - name: 'Run Azure webapp deploy action using Azure Credentials'
      uses: azure/webapps-deploy@v3
      with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          slot-name: 'staging'  
          package: 'BPCalculator/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

    - name: 'Wait for 1 min after staging deployment'
      run: sleep(60)
   
    # Chrome & Chrome Driver installation
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Run Selenium tests
      run: dotnet test SeleniumTest/bin/Release/net9.0/SeleniumTest.dll /Settings:SeleniumTest.runsettings --logger:"trx;LogFileName=selenium.trx"
    #  Upload Selenium test results as artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Selenium Tests Output
        path: '**/TestResults/**/*.trx'
        
  grafana_k6_performance_test:
    needs: build
    uses: ./.github/workflows/grafana-k6-test.yml # execute performance tests using Grafana k6

  full-deployment:
    name: 'Swap staging and production slots'
    needs: grafana_k6_performance_test
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PERSONAL_ACCOUNT }}

    - name: Swap staging and production slots
      run: |
        az webapp deployment slot swap --name bp-calc-personal-acc --resource-group Lab1-VStudio --slot staging --target-slot production
       
      

