name: Pen Testing w/ ZAP

env:
  URI: https://bp-calc.azurewebsites.net/           
  
on:
  workflow_dispatch:               
  workflow_call:  # making it reusable workflow
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Docker image for OWASP ZAP
      run: docker pull zaproxy/zap-weekly

    - name: Execute baseline scan
      run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t ${{env.URI}} -I -r zap-report.html

    - name: Check for high-severity alerts
      run: |    
        HIGH_ALERTS=$(grep -o '"risk":"High"' /report/zap-report.html | wc -l)  # This will check the report and if the high risk alerts are greater than 1 it will fail the job
        if [ "$HIGH_ALERTS" -gt 0 ]; then
          echo "$HIGH_ALERTS"
          exit 1  # This causes the job to fail
        fi
  
    - uses: actions/upload-artifact@v4
      if: always()  # Upload the report even if the check above failed
      name: upload OWASP ZAP report
      with:
        name: OWASP ZAP Report
        path: /report/zap-report.html
